FROM golang:1.22-alpine AS builder

WORKDIR /app

RUN go install github.com/cosmtrek/air@latest

# Download dependencies
COPY user-service/go.mod user-service/go.sum ./
RUN go mod download

COPY order-service .
CMD ["air", "-c", ".air.toml"]