DatabaseUrl: "nathstore:Thaicutevodoi123@@tcp(45.117.177.204:3306)/nathstore?charset=utf8&parseTime=True&loc=Local"
HttpPort: 8081


# nathstore:Thaicutevodoi123@@tcp(45.117.177.204:3306)/nathstore?charset=utf8&parseTime=True&loc=Local

# "username:password@protocol(address)/dbname?param=value",