DatabaseUrl: "postgres://user:password@192.168.1.9:54322/product_db?sslmode=disable"
HttpPort: 3306


gorm:gorm@tcp(103.159.51.238:3306)/gorm?charset=utf8&parseTime=True&loc=Local

"username:password@protocol(address)/dbname?param=value",